# Basic config for jeklly.
# Version: 0.0

# Site settings
locale : "zh-CN"
title  : "王子段 | WangZiduan "
name : &name "Wang Ziduan"
description : &description "写写代码撸撸猫,记记笔记拍拍照."
url : https://wj19816.github.io/testblog.github.io

auto: true # 修改文件时重新生成站点
future: true # Publish posts or collection documents with a future date.


# Site Author
author:
  name             : "Wang Ziduan"
  avatar           : "touxiang.png"
  bio              : "写写代码撸撸猫,记记笔记拍拍照."
  location         : "中国 北京"
  github           : "wj19816"
  weibo            : "-王子段-"


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码撸撸猫,记记笔记拍拍照.<br>You will never know unless you try."
sidebar-avatar: /img/touxiang.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Build settings
highlighter: rouge
#permalink: pretty
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
timezone: CN  # If you have timezone issue (e.g. #68) in China, uncomment to use this:


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false