# Basic config for jeklly.
# Version: 0.0

# Site settings
locale : "zh-CN"
title  : "王子段 | WangZiduan "
name : &name "Wang Ziduan"
description : &description "写写代码撸撸猫,记记笔记拍拍照."
url : https://wj19816.github.io

# Site Author
author:
  name             : "Wang Ziduan"
  avatar           : "touxiang.png"
  bio              : "写写代码撸撸猫,记记笔记拍拍照."
  location         : "中国 北京"
  github           : "wj19816"
  weibo            : "-王子段-"




# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>You will never know unless you try."
sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# 修改文件时重新生成站点
auto: true
# Publish posts or collection documents with a future date.
future: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
